tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install

     
      mkdir -p /home/gitpod/.aws

     
      echo "[default]" > /home/gitpod/.aws/credentials
      echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> /home/gitpod/.aws/credentials
      echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> /home/gitpod/.aws/credentials

      echo "[default]" > /home/gitpod/.aws/config
      echo "region=${AWS_DEFAULT_REGION:-us-west-1}" >> /home/gitpod/.aws/config
      echo "output=json" >> /home/gitpod/.aws/config

      cd $THEIA_WORKSPACE_ROOT
