tasks:
  - name: utils
    before:
      sudo apt-get install tree
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT


# chmod u+x s3/bash-scripts/create-bucket -- this command puts the create-bucket file into execution
# so whenever we create new files, gotta use it to put it into execution
