#!/usr/bin/env bash

echo "==creating bucket"

if [ -z "$1" ]; then
    echo "This is not how you name a bucket. Usage: ./create-bucket <bucket-name>"
    exit 1
fi

BUCKET_NAME=$1

LOCATION=$(aws s3api create-bucket \
--bucket $BUCKET_NAME \
--create-bucket-configuration="LocationConstraint=us-west-1" \
--query Location \
--output text)

echo "Bucket is Created: $LOCATION"
