#!/usr/bin/env bash
echo "== put-object"

# set -x
# check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a BucketName. Usage: ./put-object <bucket-name> <file-path>"
    exit 1
fi

# Check for filename
if [ -z "$2" ]; then
    echo "There needs to be a filename. Usage: ./put-object <bucket-name> <file-path>"
    exit 1
fi

BUCKET_NAME=$1
FILENAME=$2

OBJECT_KEY=$(basename "$FILENAME")

aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILENAME \
--key $OBJECT_KEY